### ISSUE TITLE
Is the Sekai Wishlist dead?

### ISSUE THREAD

**Issue by BentleyBentayga** [TitusEfferian/sekai-wishlist#4]
![image](https://user-images.githubusercontent.com/94912171/176790641-f933be36-ed04-4fb0-9ff9-ac801a383fc6.png)
June has passed and the entire month still never had any updates. Is this website discontinued or dead, or making a masssive update?

**Comment by TitusEfferian** [comment]
Hello @BentleyBentayga 
the website is still up, and working fine. Currently we have 200+ wishlist and submission. We are slowing down the daily / weekly update so the current available wishlist can be discover by anyone for a while.

will be update soon

thank you

**Comment by BentleyBentayga** [comment]
@TitusEfferian please update now, it is too long to stay here.

**Comment by BentleyBentayga** [comment]
I AM GETTING WORRIED THAT THIS HAS BEEN A MONTH SINCE THE WEBSITE NEVER HAD ANY DAILY UPDATES, PLEASE UPDATE IT RIGHT NOW! UPDATE IT RIGHT NOW! IT HAS BEEN 8 DAYS SINCE THERE'S NO REPLY! THIS DESPERATELY NEEDED AN UPDATE! TITUSEFFERIAN PLEASE UPDATE THE WISHLIST NOW! UPDATE IT NOW! RESPOND TO ME NOW!

To @TitusEfferian

**Comment by BentleyBentayga** [comment]
@TitusEfferian the wishlist has been updated, you can check out there: https://wishlist.sekai.best/
